filegroup(
    name = "runner_template",
    srcs = ["appengine_runner.sh.template"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "deploy_template",
    srcs = ["appengine_deploy.sh.template"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sdk_build_file",
    srcs = ["sdk.BUILD"],
    visibility = ["//visibility:public"],
)
