load("//appengine:appengine.bzl", "appengine_war")

appengine_war(
    name = "examples",
    data = ["//examples/webapp"],
    data_path = "/examples/webapp",
    jars = ["//examples/src:src_deploy.jar"],
)
