java_binary(
    name = "src",
    srcs = ["App.java"],
    visibility = ["//examples/java:__pkg__"],
    deps = [
        "//appengine:javax.servlet.api",
        "@com_google_appengine_java//:api",
    ],
)
